# -*- coding: utf-8 -*-
"""단속+보호구역.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VK-P1EqJwKJqWGDs5Qk5ZAg_EGFY7pr4
"""

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/(격자)_202204"

import json

# 실습: 필요한 라이브러리 설치 (이미 설치되어 있다면 건너뛸 수 있습니다)
! pip install panel datashader hvplot jupyter_bokeh
# pip install -r requirements.txt

import geopandas as gpd
import matplotlib.pyplot as plt

seoul_grid = gpd.read_file(path)

seoul_grid.plot(color="lightgrey", edgecolor="black", linewidth=0.5)
plt.title("서울시 격자 지도")
plt.show()

"""단속카메라"""

import pandas as pd
from pyproj import Proj, transform
from shapely.geometry import Point

# 1. 단속카메라 데이터 로드
cam_202201 = pd.read_excel('/content/drive/MyDrive/과속단속카메라 2022샘플.xlsx')
cam_202201.head()

pip install geopandas pyproj matplotlib

#좌표계 변환

import pandas as pd
from pyproj import Transformer

transformer = Transformer.from_crs("EPSG:4326", "EPSG:5179", always_xy=True)

def transform_coordinates(row):
    lon, lat = row['경도'], row['위도']
    tm_x, tm_y = transformer.transform(lon, lat)
    return pd.Series({'tm_x': tm_x, 'tm_y': tm_y})

cam_202201[['tm_x', 'tm_y']]= cam_202201.apply(transform_coordinates, axis=1)

print(cam_202201.head())

geometry = [Point(xy) for xy in zip(cam_202201["tm_x"], cam_202201["tm_y"])]
fig, ax = plt.subplots(figsize=(12, 12))

seoul_grid.plot(ax=ax, color="lightgrey", edgecolor="black", linewidth=0.5)

cam_202201_gdf = gpd.GeoDataFrame(cam_202201, geometry=geometry)
cam_202201_gdf.plot(ax=ax, color="red", markersize=10, alpha=0.7, label="카메라 위치")

# 공간 조인: 카메라 포함된 격자
cams_grid = gpd.sjoin(cam_202201_gdf, seoul_grid, how="inner", predicate="intersects")

print(cams_grid.head())